version: '3.8'

services:
  valleycoin:
    build:
      context: https://github.com/woogim/valleycoin.git#main
      dockerfile: Dockerfile.server
    expose:
      - 5000
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://valleycoin-postgres-1:${DB_PASSWORD}@postgres:5432/valleycoin
      - PGDATABASE=valleycoin
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=valleycoin
      - PGPASSWORD=${DB_PASSWORD}
    depends_on:
      - postgres
    networks:
      - caddy_gateway
      - internal_network
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=valleycoin
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=valleycoin
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/dump:/docker-entrypoint-initdb.d
    networks:
      - caddy_gateway
      - internal_network
    restart: unless-stopped

networks:
  caddy_gateway:
    external: true
  internal_network:
    internal: true

volumes:
  postgres-data: